package desafio.ejb.tipoEquipamento;

import javax.ejb.EntityBean;
import javax.ejb.CreateException;
import weblogic.ejb.GenericEntityBean;
import weblogic.ejbgen.Entity;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.CmpField;
import weblogic.ejbgen.LocalMethod;

/**
 * GenericEntityBean subclass automatically generated by OEPE.
 *
 * Please update the ejbCreate and ejbPostCreate methods as needed to properly initialize new instances
 * of your bean. Also, review primary key field methods and the Entity and JndiName annotations
 * to ensure the settings match the bean's intended use.
 */
@Entity(ejbName = "TipoEquipamentoBean", dataSourceName = "cgDataSource", tableName = "TipoEquipamentoBean", primKeyClass = "java.lang.Integer")
@JndiName(local = "ejb.TipoEquipamentoBeanLocalHome")
@FileGeneration(localClass = Constants.Bool.TRUE, localHome = Constants.Bool.TRUE, remoteClass = Constants.Bool.FALSE, remoteHome = Constants.Bool.FALSE, valueClass = Constants.Bool.TRUE)
abstract public class TipoEquipamentoBean extends GenericEntityBean implements
		EntityBean {
	/**
	 * IMPORTANT: Automatically generated ejbCreate() method.
	 * Please change as appropriate.
	 */
	public java.lang.Integer ejbCreate(java.lang.Integer key)
			throws CreateException {
		setKey(key);
		return null;
	}

	/**
	 * IMPORTANT: Automatically generated ejbPostCreate() method.
	 * Please change as appropriate.
	 */
	public void ejbPostCreate(java.lang.Integer key) {
	}

	/**
	 * IMPORTANT: Automatically generated primary key field getter method. 
	 * Please change name and class as appropriate.
	 */
	@CmpField(column = "key", primkeyField = Constants.Bool.TRUE)
	@LocalMethod()
	public abstract java.lang.Integer getKey();

	/**
	 * IMPORTANT: Automatically generated primary key field setter method. 
	 * Please change name and class as appropriate.
	 */
	@LocalMethod()
	public abstract void setKey(java.lang.Integer key);
}