package desafio.ejb.manager;

import javax.ejb.EJBException;
import javax.ejb.SessionBean;

import desafio.ejb.localizacao.LocalizacaoBean;
import desafio.ejb.localizacao.LocalizacaoBeanLocal;
import desafio.ejb.localizacao.LocalizacaoBeanLocalHome;
import desafio.localizacao.LocalizacaoVO;
import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Session;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.Constants;

/**
 * GenericSessionBean subclass automatically generated by OEPE.
 *
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 */
@Session(ejbName = "LocalizacaoSession")
@JndiName(remote = "ejb.LocalizacaoSessionRemoteHome")
@FileGeneration(remoteClass = Constants.Bool.TRUE, remoteHome = Constants.Bool.TRUE, localClass = Constants.Bool.FALSE, localHome = Constants.Bool.FALSE)
public class LocalizacaoSession extends GenericSessionBean implements
		SessionBean {
	private static final long serialVersionUID = 1L;

	private LocalizacaoBeanLocal localizacao;
	private LocalizacaoBeanLocalHome localizacaoHome;
	
	public void ejbCreate() {
		// IMPORTANT: Add your code here
	}

	private void inicializa(LocalizacaoVO localizacaoVO) throws EJBException {
		
		this.localizacao = null;
		this.localizacaoHome = null;
		
		try {
			this.localizacaoHome = LocalizacaoBean.getHome(); // todo
			if(localizacaoVO != null && localizacaoVO.getId() > 0){
				this.localizacao = this.localizacaoHome.findByPrimaryKey(localizacaoVO.getId());
			}
		} catch (Exception e) {
			throw new EJBException(e);
		}
	}

}