package desafio.ejb.usuario;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 10.3.6.0  Tue Nov 15 08:52:36 PST 2011 1441050 
*/


import java.io.Serializable;

// BEGIN imports from bean class
import javax.ejb.CreateException;
import javax.ejb.EntityBean;
import weblogic.ejb.GenericEntityBean;
import weblogic.ejbgen.CmpField;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.Entity;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.LocalMethod;
// END imports from bean class


public class UsuarioBeanValue  implements Serializable  {

  public UsuarioBeanValue() {}

  public UsuarioBeanValue(java.lang.Integer id, java.lang.String nome) {
    m_id = id;
    m_nome = nome;
  }

  public java.lang.Integer toPK() {
    return m_id;
  }

  private java.lang.Integer m_id;
  public java.lang.Integer getId(){
    return m_id;
  }

  public void setId(java.lang.Integer n){
    m_id = n;
  }  private java.lang.String m_nome;
  public java.lang.String getNome(){
    return m_nome;
  }

  public void setNome(java.lang.String n){
    m_nome = n;
  }

  public String toString() {
    StringBuffer result = new StringBuffer("[UsuarioBeanValue ");
    result.append(  " id:" + m_id +   " nome:" + m_nome);
    result.append("]");
    return result.toString();
  }

  private int m_hashCode = 0;
  public int hashCode() {
    if (0 == m_hashCode) {
      m_hashCode = 
                            (null != m_id ? m_id.hashCode() : 0)
                              ^
                (null != m_nome ? m_nome.hashCode() : 0)
                      ;
    }
    
    return m_hashCode;
  }

  public boolean equals(Object other) {
    if (other == this) return true;
    if (null == other) return false;
    if (other.hashCode() != hashCode()) return false;
    try {
      UsuarioBeanValue other2 = ( UsuarioBeanValue ) other;
            return
                      (safeEquals(this.m_id, other2.m_id))
                                  &&
                (safeEquals(this.m_nome, other2.m_nome))
                      ;
    }
    catch(ClassCastException ex) {
      return false;
    }
  }
  
  private boolean safeEquals(Object o1, Object o2) {
    if (null == o1 && null == o2) return true;
    if (null == o1 && null != o2) return false;
    if (null != o1 && null == o2) return false;
    return o1.equals(o2);
  }
  
}
